### ISSUE TITLE
Where to put GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET ?

### ISSUE THREAD

**Issue by Jehu** [Mordorreal/redmine_document_library_gdrive#6]
I've added them to config/configuration.yml

```
production:
  GOOGLE_CLIENT_ID: my-id
  GOOGLE_CLIENT_SECRET: my-secret
  email_delivery:
    [...]
```

.. and restarted Redmine but nothing has changed at the settings page (settings/plugin/redmine_document_library_gdrive). 

There is still the Text

> Input setting that you get from Google in application environments
> GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET and restart application.
> After this you can attach Gdrive account to Redmine.

Any hints?
